config/routes.rb
Wallet::Application.routes.draw do
  resources :conceptos
  resources :movimientos

  root :to => 'inicio#index'

end

app/models/concepto.rb
class Concepto < ActiveRecord::Base
  attr_accessible :descripcion, :es_egreso, :es_ingreso

  validates :descripcion, :presence => true,
                          :length => { :minimum => 3 }

  has_many :movimientos
end

app/models/movimiento.rb
class Movimiento < ActiveRecord::Base
  attr_accessible :anio, :mes, :monto, :concepto_id
  belongs_to :concepto

  validates :anio, :length => { :is => 4 }
  validates :mes, :length => { :is => 2 }
  validates :monto, :presence => true,
                    :numericality => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/conceptos_controller.rb
class ConceptosController < ApplicationController
  # GET /conceptos
  # GET /conceptos.json
  def index
    @conceptos = Concepto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conceptos }
    end
  end

  # GET /conceptos/1
  # GET /conceptos/1.json
  def show
    @concepto = Concepto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concepto }
    end
  end

  # GET /conceptos/new
  # GET /conceptos/new.json
  def new
    @concepto = Concepto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concepto }
    end
  end

  # GET /conceptos/1/edit
  def edit
    @concepto = Concepto.find(params[:id])
  end

  # POST /conceptos
  # POST /conceptos.json
  def create
    @concepto = Concepto.new(params[:concepto])

    respond_to do |format|
      if @concepto.save
        format.html { redirect_to @concepto, notice: 'Concepto was successfully created.' }
        format.json { render json: @concepto, status: :created, location: @concepto }
      else
        format.html { render action: "new" }
        format.json { render json: @concepto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conceptos/1
  # PUT /conceptos/1.json
  def update
    @concepto = Concepto.find(params[:id])

    respond_to do |format|
      if @concepto.update_attributes(params[:concepto])
        format.html { redirect_to @concepto, notice: 'Concepto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concepto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conceptos/1
  # DELETE /conceptos/1.json
  def destroy
    @concepto = Concepto.find(params[:id])
    @concepto.destroy

    respond_to do |format|
      format.html { redirect_to conceptos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  
  def index
    @title = "Home"
  end


end

app/controllers/movimientos_controller.rb
class MovimientosController < ApplicationController
  # GET /movimientos
  # GET /movimientos.json
  def index
    @movimientos = Movimiento.order("anio DESC, mes DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movimientos }
    end
  end

  # GET /movimientos/1
  # GET /movimientos/1.json
  def show
    @movimiento = Movimiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movimiento }
    end
  end

  # GET /movimientos/new
  # GET /movimientos/new.json
  def new
    @movimiento = Movimiento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movimiento }
    end
  end

  # GET /movimientos/1/edit
  def edit
    @movimiento = Movimiento.find(params[:id])
  end

  # POST /movimientos
  # POST /movimientos.json
  def create
    @movimiento = Movimiento.new(params[:movimiento])

    respond_to do |format|
      if @movimiento.save
        format.html { redirect_to @movimiento, notice: 'Movimiento was successfully created.' }
        format.json { render json: @movimiento, status: :created, location: @movimiento }
      else
        format.html { render action: "new" }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movimientos/1
  # PUT /movimientos/1.json
  def update
    @movimiento = Movimiento.find(params[:id])

    respond_to do |format|
      if @movimiento.update_attributes(params[:movimiento])
        format.html { redirect_to @movimiento, notice: 'Movimiento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimientos/1
  # DELETE /movimientos/1.json
  def destroy
    @movimiento = Movimiento.find(params[:id])
    @movimiento.destroy

    respond_to do |format|
      format.html { redirect_to movimientos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conceptos_helper.rb
module ConceptosHelper
end

app/helpers/movimientos_helper.rb
module MovimientosHelper
end

app/views/conceptos/_form.html.erb
<%= form_for(@concepto) do |f| %>
  <% if @concepto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concepto.errors.count, "error") %> prohibited this concepto from being saved:</h2>

      <ul>
      <% @concepto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :es_ingreso %><br />
    <%= f.check_box :es_ingreso %>
  </div>
  <div class="field">
    <%= f.label :es_ingreso %><br />
    <%= f.check_box :es_egreso %>
  </div>
  <div class="actions">
    <%=submit_tag "Guardar" %>
  </div>
<% end %>

app/views/conceptos/edit.html.erb
<h1>Editando concepto</h1>

<%= render 'form' %>

<%= link_to 'Show', @concepto %> |
<%= link_to 'Back', conceptos_path %>

app/views/conceptos/index.html.erb
<h1>Conceptos</h1>

<table>
  <tr>
    <th>Descripci&oacuten</th>
    <th>Es ingreso</th>
    <th>Es egreso</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conceptos.each do |concepto| %>
  <tr>
    <td><%= concepto.descripcion %></td>
    <td><%= concepto.es_ingreso %></td>
    <td><%= concepto.es_egreso %></td>
    <td><%= link_to 'Show', concepto %></td>
    <td><%= link_to 'Edit', edit_concepto_path(concepto) %></td>
    <td><%= link_to 'Destroy', concepto, method: :delete, data: { confirm: 'Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Concepto', new_concepto_path %>

app/views/conceptos/new.html.erb
<h1>Nuevo concepto</h1>

<%= render 'form' %>


<%= link_to 'Conceptos', conceptos_path %>

app/views/conceptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripci&oacuten:</b>
  <%= @concepto.descripcion %>
</p>

<p>
  <b>Es ingreso:</b>
  <%= @concepto.es_ingreso %>
</p>

<p>
  <b>Es egreso:</b>
  <%= @concepto.es_egreso %>
</p>


<%= link_to 'Editar', edit_concepto_path(@concepto) %> |
<%= link_to 'Conceptos', conceptos_path %>

app/views/inicio/index.html.erb
<div>
<h4>Primer intento para el sofwtare de control de ingresos y egresos</h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<section id="navbar">

  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="width: auto;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="../">Wallet</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"> <%= link_to "Movimientos", movimientos_path %></li>            
            <li class="active"> <%= link_to "Conceptos", conceptos_path %></li>    
          </ul>

        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div><!-- /navbar -->


<div class="span6">
<%= yield %>
</div>

</body>
</html>

app/views/movimientos/_form.html.erb
<%= form_for(@movimiento) do |f| %>
  <% if @movimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movimiento.errors.count, "error") +' '+ I18n.t('.abc.no_guarda')%>: </h2>

      <ul>
      <% @movimiento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label I18n.t('.abc.concepto') %><br />
    <%= f.select :concepto_id, Concepto.find(:all).collect{|t|[t.descripcion, t.id]} %>
  </div>
  <div class="field">
    <%= f.label I18n.t('.abc.mes') %><br />
    <%= f.number_field :mes %>
  </div>
  <div class="field">
    <%= f.label I18n.t('.abc.anio') %><br />
    <%= f.number_field :anio %>
  </div>
  <div class="field">
    <%= f.label I18n.t('.abc.monto') %><br />
    <%= f.text_field :monto %>
  </div>
  <div class="actions">
    <%=f.submit%>
  </div>
<% end %>

app/views/movimientos/edit.html.erb
<h1><%=I18n.t('.abc.edit') + ' ' +I18n.t('.abc.movimiento')%></h1>

<%= render 'form' %>

<%= link_to I18n.t('.abc.show'), @movimiento %> |
<%= link_to I18n.t('.abc.volver'), movimientos_path %>

app/views/movimientos/index.html.erb
<h1><%=I18n.t('.abc.movimientos') %></h1>

<table>
  <tr>
    <th><%=I18n.t('.abc.concepto') %></th>  
    <th><%=I18n.t('.abc.mes') %></th>
    <th><%=I18n.t('.abc.anio') %></th>
    <th><%=I18n.t('.abc.monto') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movimientos.each do |movimiento| %>
  <tr>
    <td><%= movimiento.concepto.descripcion %></td>
    <td><%= movimiento.mes %></td>
    <td><%= movimiento.anio %></td>
    <td><%= movimiento.monto %></td>
    <td><%= link_to I18n.t('.abc.show') , movimiento %></td>
    <td><%= link_to I18n.t('.abc.edit'), edit_movimiento_path(movimiento) %></td>
    <td><%= link_to I18n.t('.abc.destroy'), movimiento, method: :delete, data: { confirm: I18n.t('.abc.confirm')} %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to I18n.t('.abc.new'), new_movimiento_path %>

app/views/movimientos/new.html.erb
<h1><%=I18n.t('.abc.new') + ' ' +I18n.t('.abc.movimiento')%></h1>

<%= render 'form' %>

<%= link_to I18n.t('.abc.volver'), movimientos_path %>

app/views/movimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%=I18n.t('.abc.concepto') %>:</b>
  <%= @movimiento.concepto.descripcion %>
</p>

<p>
  <b><%=I18n.t('.abc.mes') %>:</b>
  <%= @movimiento.mes %>
</p>

<p>
  <b><%=I18n.t('.abc.anio') %>:</b>
  <%= @movimiento.anio %>
</p>

<p>
  <b><%=I18n.t('.abc.monto') %>:</b>
  <%= @movimiento.monto %>
</p>


<%= link_to I18n.t('.abc.edit'), edit_movimiento_path(@movimiento) %> |
<%= link_to I18n.t('.abc.volver'), movimientos_path %>